// File generated by FlutterFire CLI — replace with your project or run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until then, placeholders allow the app to build; push stays disabled until
// [DefaultFirebaseOptions] matches your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Titra push is not configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported on this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMhwN6l-P79Kzp7Gvs6er070Pinq3rSk',
    appId: '1:226030329230:android:7b87badfbb7a9d844d18df',
    messagingSenderId: '226030329230',
    projectId: 'titra-672b0',
    storageBucket: 'titra-672b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDiwBORPE0-7yN2r7Epdi0nnZBE8Lwp0U',
    appId: '1:226030329230:ios:17d15d9b4210b92e4d18df',
    messagingSenderId: '226030329230',
    projectId: 'titra-672b0',
    storageBucket: 'titra-672b0.firebasestorage.app',
    iosBundleId: 'com.shahir.titra',
  );

}